version: '3.8'

services:
  web:
    build: ./djangobnb_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djangobnb_backend/:/usr/src/djangobnb_backend/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  celery:
    build: ./djangobnb_backend
    command: celery -A djangobnb_backend worker --loglevel=info
    volumes:
      - ./djangobnb_backend/:/usr/src/djangobnb_backend/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  celery-beat:
    build: ./djangobnb_backend
    command: celery -A djangobnb_backend beat --loglevel=info
    volumes:
      - ./djangobnb_backend/:/usr/src/djangobnb_backend/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=djangobnb

  redis:
    image: redis:7.0.11-alpine

volumes:
  postgres_data:
