# Generated by Django 5.0.7 on 2024-08-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_category_alter_property_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='feedback_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
    ]
